server:
  port: 8080

logging:
  file:
    path: spring.log

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.153.128:3306/mybatisTest?serverTimezone=GMT
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.maoyan.model
  mapper-locations:
    - mapper/*
